- name: Deploy project
  hosts: all
  gather_facts: no
  roles:
    - geerlingguy.pip

  vars:
    pip_install_packages:
      - name: docker

  tasks:
    - name: start app
      community.docker.docker_container:
        name: app
        image: "redmine:5.0.2-bullseye"
        restart_policy: always
        state: started
        ports:
          - "80:3000"
          - "443:3000"